plugin: aws_ec2

#aws_access_key: AKIATBDLAVQ6B2VE3R5I 
#aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
